//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSync.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlowSyncInfrastructureResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowSyncInfrastructureResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSync.Infrastructure.FlowSyncInfrastructureResource", typeof(FlowSyncInfrastructureResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not found..
        /// </summary>
        internal static string ConfigurationManagerItemNotFoumd {
            get {
                return ResourceManager.GetString("ConfigurationManagerItemNotFoumd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value from ({0}) could not be extracted!.
        /// </summary>
        internal static string DateParserCannotExtractValue {
            get {
                return ResourceManager.GetString("DateParserCannotExtractValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given datetime is not valid!.
        /// </summary>
        internal static string DateParserInvalidInput {
            get {
                return ResourceManager.GetString("DateParserInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type {0} is not valid!.
        /// </summary>
        internal static string NamespaceParserInvalidType {
            get {
                return ResourceManager.GetString("NamespaceParserInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string NewtonsoftDeserializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("NewtonsoftDeserializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string NewtonsoftSerializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("NewtonsoftSerializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in initializing &apos;{0}&apos; plugin instance!.
        /// </summary>
        internal static string PlugininItializingInstanceErrorMessage {
            get {
                return ResourceManager.GetString("PlugininItializingInstanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} could not found!.
        /// </summary>
        internal static string PluginsManagerCouldNotFoumd {
            get {
                return ResourceManager.GetString("PluginsManagerCouldNotFoumd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value from ({0}) could not be extracted!.
        /// </summary>
        internal static string SizeParserCannotExtractValue {
            get {
                return ResourceManager.GetString("SizeParserCannotExtractValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given size is not valid!.
        /// </summary>
        internal static string SizeParserInvalidInput {
            get {
                return ResourceManager.GetString("SizeParserInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property. Order By Format: Property, Property2 ASC, Property2 DESC.
        /// </summary>
        internal static string SortParserInvalidProperty {
            get {
                return ResourceManager.GetString("SortParserInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property. Given sorting property name &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string SortParserInvalidPropertyName {
            get {
                return ResourceManager.GetString("SortParserInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction &apos;{0}&apos; for &apos;{1}&apos; is not valid..
        /// </summary>
        internal static string SortParserInvalidSortDirection {
            get {
                return ResourceManager.GetString("SortParserInvalidSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sorting string &apos;{0}&apos;. Order By Format: Property, Property2 ASC, Property2 DESC.
        /// </summary>
        internal static string SortParserInvalidSortingTerm {
            get {
                return ResourceManager.GetString("SortParserInvalidSortingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected plugin type &apos;{0}&apos; is not valid storage plugin type..
        /// </summary>
        internal static string StorageNormsParserInvalidStorageType {
            get {
                return ResourceManager.GetString("StorageNormsParserInvalidStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; storage not found!.
        /// </summary>
        internal static string StorageNormsParserStorageNotFoumd {
            get {
                return ResourceManager.GetString("StorageNormsParserStorageNotFoumd", resourceCulture);
            }
        }
    }
}
