//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfrastructureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Infrastructure.Localization.InfrastructureResources", typeof(InfrastructureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not found..
        /// </summary>
        internal static string ExpressionParser_KeyNotFound {
            get {
                return ResourceManager.GetString("ExpressionParser_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonDeserializer_InputValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonDeserializer_InputValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonDeserializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonDeserializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonSerializer_InputValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonSerializer_InputValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonSerializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonSerializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not valid!.
        /// </summary>
        internal static string Logging_Invalid_Property {
            get {
                return ResourceManager.GetString("Logging_Invalid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt {0} failed: {1}..
        /// </summary>
        internal static string RetryService_AttemptFailed {
            get {
                return ResourceManager.GetString("RetryService_AttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; failed after {1} attempts..
        /// </summary>
        internal static string RetryService_OperationFailedAfterAttempts {
            get {
                return ResourceManager.GetString("RetryService_OperationFailedAfterAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry mechanism failed unexpectedly..
        /// </summary>
        internal static string RetryService_RetryFailedUnexpectedly {
            get {
                return ResourceManager.GetString("RetryService_RetryFailedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; canceled..
        /// </summary>
        internal static string RetryService_TaskCanceled {
            get {
                return ResourceManager.GetString("RetryService_TaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before retry....
        /// </summary>
        internal static string RetryService_WaitingBeforeRetry {
            get {
                return ResourceManager.GetString("RetryService_WaitingBeforeRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow execution canceled..
        /// </summary>
        internal static string RetryService_WorkflowCanceled {
            get {
                return ResourceManager.GetString("RetryService_WorkflowCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DefaultProvider &apos;{0}&apos;. Must be one of: {1}.
        /// </summary>
        internal static string SecretConfiguration_InvalidProvider {
            get {
                return ResourceManager.GetString("SecretConfiguration_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DefaultScheme &apos;{0}&apos;. Must be one of: {1}.
        /// </summary>
        internal static string SecurityConfiguration_InvalidScheme {
            get {
                return ResourceManager.GetString("SecurityConfiguration_InvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specification(s) [{0}] are required and must have value..
        /// </summary>
        internal static string SpecificationsMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; in specifications is required and must have a value..
        /// </summary>
        internal static string SpecificationsRequiredMemberMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsRequiredMemberMustHaveValue", resourceCulture);
            }
        }
    }
}
