//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Infrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output &apos;{0}&apos; not found..
        /// </summary>
        internal static string ExpressionParser_OutputNotFound {
            get {
                return ResourceManager.GetString("ExpressionParser_OutputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonDeserializer_InputValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonDeserializer_InputValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonDeserializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonDeserializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonSerializer_InputValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonSerializer_InputValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonSerializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonSerializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not valid!.
        /// </summary>
        internal static string Logging_Invalid_Property {
            get {
                return ResourceManager.GetString("Logging_Invalid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files deleted successfully..
        /// </summary>
        internal static string Plugin_Download_Extraction_AllFilesDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_AllFilesDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: &apos;{0}&apos;.
        /// </summary>
        internal static string Plugin_Download_Extraction_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting files: {0}.
        /// </summary>
        internal static string Plugin_Download_Extraction_ErrorDuringDelete {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_ErrorDuringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin successfully extracted to: &apos;{0}&apos;.
        /// </summary>
        internal static string Plugin_Download_Extraction_Successfully {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} {1}. Failed to fetch data from URL..
        /// </summary>
        internal static string Plugin_Download_FailedToFetchDataFromUrl {
            get {
                return ResourceManager.GetString("Plugin_Download_FailedToFetchDataFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin with type &apos;{0}&apos; and version &apos;{1}&apos; found..
        /// </summary>
        internal static string Plugin_Download_PluginNotFound {
            get {
                return ResourceManager.GetString("Plugin_Download_PluginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin loaded successfully..
        /// </summary>
        internal static string Plugin_Handle_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("Plugin_Handle_LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load plugin: {0}.
        /// </summary>
        internal static string Plugin_Loader_FailedToLoadPlugin {
            get {
                return ResourceManager.GetString("Plugin_Loader_FailedToLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin file not found: {0}.
        /// </summary>
        internal static string Plugin_Loader_FileNotFound {
            get {
                return ResourceManager.GetString("Plugin_Loader_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin type found..
        /// </summary>
        internal static string Plugin_Loader_NoPluginFound {
            get {
                return ResourceManager.GetString("Plugin_Loader_NoPluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while extracting the package: {0}.
        /// </summary>
        internal static string PluginDownloader_ErrorInExtractingPackage {
            get {
                return ResourceManager.GetString("PluginDownloader_ErrorInExtractingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; has associated configurations. Please remove the existing configuration(s) before proceeding..
        /// </summary>
        internal static string PluginManager_AssociatedPluginConfigIsExist {
            get {
                return ResourceManager.GetString("PluginManager_AssociatedPluginConfigIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum validation failed. Package may be corrupted or tampered with..
        /// </summary>
        internal static string PluginManager_Install_ChecksumValidationFailed {
            get {
                return ResourceManager.GetString("PluginManager_Install_ChecksumValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}..
        /// </summary>
        internal static string PluginManager_Install_ErrorLoading {
            get {
                return ResourceManager.GetString("PluginManager_Install_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; v{1} installed successfully..
        /// </summary>
        internal static string PluginManager_Install_PluginInstalledSuccessfully {
            get {
                return ResourceManager.GetString("PluginManager_Install_PluginInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; is already exist..
        /// </summary>
        internal static string PluginManager_Install_PluginIsAlreadyExist {
            get {
                return ResourceManager.GetString("PluginManager_Install_PluginIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; not found!.
        /// </summary>
        internal static string PluginManager_PluginCouldNotFound {
            get {
                return ResourceManager.GetString("PluginManager_PluginCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; version &apos;{1}&apos; is uninstalled successfully..
        /// </summary>
        internal static string PluginManager_PluginUninstalledSuccessfully {
            get {
                return ResourceManager.GetString("PluginManager_PluginUninstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} could not found!.
        /// </summary>
        internal static string PluginServiceCouldNotFoundPlugin {
            get {
                return ResourceManager.GetString("PluginServiceCouldNotFoundPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration &apos;{0}&apos; could be not found..
        /// </summary>
        internal static string PluginTypeService_ConfigurationCouldNotFound {
            get {
                return ResourceManager.GetString("PluginTypeService_ConfigurationCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin with type &apos;{0}&apos; and version &apos;{1}&apos; could be not found..
        /// </summary>
        internal static string PluginTypeService_PluginCouldNotFound {
            get {
                return ResourceManager.GetString("PluginTypeService_PluginCouldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin with type &apos;{0}&apos; and version &apos;{1}&apos; could be not load..
        /// </summary>
        internal static string PluginTypeService_PluginCouldNotLoad {
            get {
                return ResourceManager.GetString("PluginTypeService_PluginCouldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt {0} failed: {1}..
        /// </summary>
        internal static string RetryService_AttemptFailed {
            get {
                return ResourceManager.GetString("RetryService_AttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; failed after {1} attempts..
        /// </summary>
        internal static string RetryService_OperationFailedAfterAttempts {
            get {
                return ResourceManager.GetString("RetryService_OperationFailedAfterAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry mechanism failed unexpectedly..
        /// </summary>
        internal static string RetryService_RetryFailedUnexpectedly {
            get {
                return ResourceManager.GetString("RetryService_RetryFailedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; timeout on attempt {1}..
        /// </summary>
        internal static string RetryService_TaskTimeoutOnAttempt {
            get {
                return ResourceManager.GetString("RetryService_TaskTimeoutOnAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before retry....
        /// </summary>
        internal static string RetryService_WaitingBeforeRetry {
            get {
                return ResourceManager.GetString("RetryService_WaitingBeforeRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow execution timeout.
        /// </summary>
        internal static string RetryService_WorkflowTimeout {
            get {
                return ResourceManager.GetString("RetryService_WorkflowTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specification(s) [{0}] are required and must have value..
        /// </summary>
        internal static string SpecificationsMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; in specifications is required and must have a value..
        /// </summary>
        internal static string SpecificationsRequiredMemberMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsRequiredMemberMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string Workflow_ExecutionTracker_NoWorkflowExecutionFound {
            get {
                return ResourceManager.GetString("Workflow_ExecutionTracker_NoWorkflowExecutionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow task with name &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string Workflow_ExecutionTracker_NoWorkflowTaskExecutionFound {
            get {
                return ResourceManager.GetString("Workflow_ExecutionTracker_NoWorkflowTaskExecutionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow execution with Id: &apos;{0}&apos; was completed successfully..
        /// </summary>
        internal static string Workflow_Executor_CompletedSuccessfully {
            get {
                return ResourceManager.GetString("Workflow_Executor_CompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has cyclic dependencies. Please resolve them and try again!. There are Cyclic: {0}.
        /// </summary>
        internal static string Workflow_Executor_CyclicDependencies {
            get {
                return ResourceManager.GetString("Workflow_Executor_CyclicDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a duplicated task name in the workflow tasks..
        /// </summary>
        internal static string Workflow_Executor_DuplicatedTasksName {
            get {
                return ResourceManager.GetString("Workflow_Executor_DuplicatedTasksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow execution error: {0}.
        /// </summary>
        internal static string Workflow_Executor_ErrorInExecution {
            get {
                return ResourceManager.GetString("Workflow_Executor_ErrorInExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are failed task in dependencies..
        /// </summary>
        internal static string Workflow_Executor_FailedDependenciesTask {
            get {
                return ResourceManager.GetString("Workflow_Executor_FailedDependenciesTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Workflow failed. Meesage: {0}.
        /// </summary>
        internal static string Workflow_Executor_GetWorkflowFailed {
            get {
                return ResourceManager.GetString("Workflow_Executor_GetWorkflowFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid workflow: missing dependencies. There are list of missing dependencies: {0}.
        /// </summary>
        internal static string Workflow_Executor_MissingDependencies {
            get {
                return ResourceManager.GetString("Workflow_Executor_MissingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workflow task execution found with name &apos;{0}&apos;.
        /// </summary>
        internal static string Workflow_Executor_NoWorkflowTaskExecutionFoumd {
            get {
                return ResourceManager.GetString("Workflow_Executor_NoWorkflowTaskExecutionFoumd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string Workflow_Executor_WorkflowCouldNotBeFound {
            get {
                return ResourceManager.GetString("Workflow_Executor_WorkflowCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initilize WorkflowExecution failed. Meesage: {0}.
        /// </summary>
        internal static string Workflow_Executor_WorkflowInitilizeFailed {
            get {
                return ResourceManager.GetString("Workflow_Executor_WorkflowInitilizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute workflow with ID &apos;{0}&apos; for user &apos;{1}&apos;..
        /// </summary>
        internal static string Workflow_TimeBased_TriggerProcessor_FailedExecution {
            get {
                return ResourceManager.GetString("Workflow_TimeBased_TriggerProcessor_FailedExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid &apos;cron&apos; expression for workflow with ID &apos;{0}&apos;..
        /// </summary>
        internal static string Workflow_TimeBased_TriggerProcessor_InvalidCornExpression {
            get {
                return ResourceManager.GetString("Workflow_TimeBased_TriggerProcessor_InvalidCornExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; failed — {1}.
        /// </summary>
        internal static string WorkflowOrchestrator_TaskFailed {
            get {
                return ResourceManager.GetString("WorkflowOrchestrator_TaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has negative Factor: &apos;{1}&apos;..
        /// </summary>
        internal static string WorkflowValidator_TaskHasNegativeFactor {
            get {
                return ResourceManager.GetString("WorkflowValidator_TaskHasNegativeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has negative Initial Delay: &apos;{1}&apos;..
        /// </summary>
        internal static string WorkflowValidator_TaskHasNegativeInitialDelay {
            get {
                return ResourceManager.GetString("WorkflowValidator_TaskHasNegativeInitialDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has negative Max Delay: &apos;{1}&apos;.
        /// </summary>
        internal static string WorkflowValidator_TaskHasNegativeMaxDelay {
            get {
                return ResourceManager.GetString("WorkflowValidator_TaskHasNegativeMaxDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &apos;{0}&apos; has negative MaxRetries: &apos;{1}&apos;..
        /// </summary>
        internal static string WorkflowValidator_TaskHasNegativeMaxRetries {
            get {
                return ResourceManager.GetString("WorkflowValidator_TaskHasNegativeMaxRetries", resourceCulture);
            }
        }
    }
}
