//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Infrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonDeserializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonDeserializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value can&apos;t be empty or null..
        /// </summary>
        internal static string JsonSerializerValueCanNotBeEmpty {
            get {
                return ResourceManager.GetString("JsonSerializerValueCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not valid!.
        /// </summary>
        internal static string Logging_Invalid_Property {
            get {
                return ResourceManager.GetString("Logging_Invalid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files deleted successfully..
        /// </summary>
        internal static string Plugin_Download_Extraction_AllFilesDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_AllFilesDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: &apos;{0}&apos;.
        /// </summary>
        internal static string Plugin_Download_Extraction_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting files: {0}.
        /// </summary>
        internal static string Plugin_Download_Extraction_ErrorDuringDelete {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_ErrorDuringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin successfully extracted to: &apos;{0}&apos;.
        /// </summary>
        internal static string Plugin_Download_Extraction_Successfully {
            get {
                return ResourceManager.GetString("Plugin_Download_Extraction_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} {1}. Failed to fetch data from URL..
        /// </summary>
        internal static string Plugin_Download_FailedToFetchDataFromUrl {
            get {
                return ResourceManager.GetString("Plugin_Download_FailedToFetchDataFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin with type &apos;{0}&apos; and version &apos;{1}&apos; found..
        /// </summary>
        internal static string Plugin_Download_PluginNotFound {
            get {
                return ResourceManager.GetString("Plugin_Download_PluginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin loaded successfully..
        /// </summary>
        internal static string Plugin_Handle_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("Plugin_Handle_LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load plugin: {0}.
        /// </summary>
        internal static string Plugin_Loader_FailedToLoadPlugin {
            get {
                return ResourceManager.GetString("Plugin_Loader_FailedToLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin file not found: {0}.
        /// </summary>
        internal static string Plugin_Loader_FileNotFound {
            get {
                return ResourceManager.GetString("Plugin_Loader_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin type found..
        /// </summary>
        internal static string Plugin_Loader_NoPluginFound {
            get {
                return ResourceManager.GetString("Plugin_Loader_NoPluginFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} could not found!.
        /// </summary>
        internal static string PluginServiceCouldNotFoundPlugin {
            get {
                return ResourceManager.GetString("PluginServiceCouldNotFoundPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt {0} failed: {1}..
        /// </summary>
        internal static string RetryService_AttemptFailed {
            get {
                return ResourceManager.GetString("RetryService_AttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed after {0} attempts..
        /// </summary>
        internal static string RetryService_OperationFailedAfterAttempts {
            get {
                return ResourceManager.GetString("RetryService_OperationFailedAfterAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry mechanism failed unexpectedly..
        /// </summary>
        internal static string RetryService_RetryFailedUnexpectedly {
            get {
                return ResourceManager.GetString("RetryService_RetryFailedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before retry....
        /// </summary>
        internal static string RetryService_WaitingBeforeRetry {
            get {
                return ResourceManager.GetString("RetryService_WaitingBeforeRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specification(s) [{0}] are required and must have value..
        /// </summary>
        internal static string SpecificationsMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; in specifications is required and must have a value..
        /// </summary>
        internal static string SpecificationsRequiredMemberMustHaveValue {
            get {
                return ResourceManager.GetString("SpecificationsRequiredMemberMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workflow task execution found with name &apos;{0}&apos;.
        /// </summary>
        internal static string Workflow_Executor_NoWorkflowTaskExecutionFoumd {
            get {
                return ResourceManager.GetString("Workflow_Executor_NoWorkflowTaskExecutionFoumd", resourceCulture);
            }
        }
    }
}
