//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSync.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlowSyncCoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowSyncCoreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSync.Core.FlowSyncCoreResource", typeof(FlowSyncCoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be not empty..
        /// </summary>
        internal static string AboutValidatorPathValueMustNotNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("AboutValidatorPathValueMustNotNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value from ({0}) could not be extracted!.
        /// </summary>
        internal static string FileSystemDateParserCannotExtractValue {
            get {
                return ResourceManager.GetString("FileSystemDateParserCannotExtractValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given datetime is not valid!.
        /// </summary>
        internal static string FileSystemDateParserInvalidInput {
            get {
                return ResourceManager.GetString("FileSystemDateParserInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; FileSystem not found!.
        /// </summary>
        internal static string FileSystemRemotePathParserFileSystemNotFoumd {
            get {
                return ResourceManager.GetString("FileSystemRemotePathParserFileSystemNotFoumd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value from ({0}) could not be extracted!.
        /// </summary>
        internal static string FileSystemSizeParserCannotExtractValue {
            get {
                return ResourceManager.GetString("FileSystemSizeParserCannotExtractValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given size is not valid!.
        /// </summary>
        internal static string FileSystemSizeParserInvalidInput {
            get {
                return ResourceManager.GetString("FileSystemSizeParserInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property. Order By Format: Property, Property2 ASC, Property2 DESC.
        /// </summary>
        internal static string FileSystemSortParserInvalidProperty {
            get {
                return ResourceManager.GetString("FileSystemSortParserInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property. Given sorting property name &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string FileSystemSortParserInvalidPropertyName {
            get {
                return ResourceManager.GetString("FileSystemSortParserInvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction &apos;{0}&apos; for &apos;{1}&apos; is not valid..
        /// </summary>
        internal static string FileSystemSortParserInvalidSortDirection {
            get {
                return ResourceManager.GetString("FileSystemSortParserInvalidSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sorting string &apos;{0}&apos;. Order By Format: Property, Property2 ASC, Property2 DESC.
        /// </summary>
        internal static string FileSystemSortParserInvalidSortingTerm {
            get {
                return ResourceManager.GetString("FileSystemSortParserInvalidSortingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation failures have occurred..
        /// </summary>
        internal static string InputValidationExceptionBaseMessage {
            get {
                return ResourceManager.GetString("InputValidationExceptionBaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind value must be [ File | Directory | FileAndDirectory ]. By default it is FileAndDirectory..
        /// </summary>
        internal static string ListValidatorKindValueMustBeValidMessage {
            get {
                return ResourceManager.GetString("ListValidatorKindValueMustBeValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be not empty..
        /// </summary>
        internal static string ListValidatorPathValueMustNotNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ListValidatorPathValueMustNotNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in initializing &apos;{0}&apos; plugin instance!.
        /// </summary>
        internal static string PlugininItializingInstanceErrorMessage {
            get {
                return ResourceManager.GetString("PlugininItializingInstanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be not empty..
        /// </summary>
        internal static string ReadValidatorPathValueMustNotNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("ReadValidatorPathValueMustNotNullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind value must be [ File | Directory | FileAndDirectory ]. By default it is FileAndDirectory..
        /// </summary>
        internal static string SizeValidatorKindValueMustBeValidMessage {
            get {
                return ResourceManager.GetString("SizeValidatorKindValueMustBeValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be not empty..
        /// </summary>
        internal static string SizeValidatorPathValueMustNotNullOrEmptyMessage {
            get {
                return ResourceManager.GetString("SizeValidatorPathValueMustNotNullOrEmptyMessage", resourceCulture);
            }
        }
    }
}
