//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Please check and ensure you using a valid credentials..
        /// </summary>
        internal static string Authentication_Access_Denied {
            get {
                return ResourceManager.GetString("Authentication_Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit details for &apos;{0}&apos; has been retrieved successfully..
        /// </summary>
        internal static string Feature_Audit_DetailesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Audit_DetailesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit details, id &apos;{0}&apos;, are not found..
        /// </summary>
        internal static string Feature_Audit_DetailsNotFound {
            get {
                return ResourceManager.GetString("Feature_Audit_DetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit list has been retrieved successfully..
        /// </summary>
        internal static string Feature_Audit_ListRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Audit_ListRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been added successfully..
        /// </summary>
        internal static string Feature_Plugin_Add_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Add_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been deleted successfully..
        /// </summary>
        internal static string Feature_Plugin_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been updated successfully..
        /// </summary>
        internal static string Feature_Plugin_Update_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Update_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been added successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Add_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Add_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config with ID &apos;{configId}&apos; was not found..
        /// </summary>
        internal static string Feature_PluginConfig_Delete_ConfigIdNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Delete_ConfigIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been deleted successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin config details for &apos;{0}&apos; has been retrieved successfully..
        /// </summary>
        internal static string Feature_PluginConfig_DetailesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_DetailesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plugin config details, id &apos;{0}&apos;, are not found..
        /// </summary>
        internal static string Feature_PluginConfig_DetailsNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_DetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Config List has been retrieved successfully..
        /// </summary>
        internal static string Feature_PluginConfig_ListRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_ListRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config with ID &apos;{configId}&apos; was not found..
        /// </summary>
        internal static string Feature_PluginConfig_Update_ConfigIdNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Update_ConfigIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been updated successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Update_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Update_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been added successfully..
        /// </summary>
        internal static string Feature_Workflow_Add_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Add_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been deleted successfully..
        /// </summary>
        internal static string Feature_Workflow_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin workflow details has been retrieved successfully..
        /// </summary>
        internal static string Feature_Workflow_Details_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Details_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_Workflow_Details_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_Workflow_Details_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin workflow has been retrieved successfully..
        /// </summary>
        internal static string Feature_Workflow_ListRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_ListRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been updated successfully..
        /// </summary>
        internal static string Feature_Workflow_Update_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Update_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_Workflow_Update_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_Workflow_Update_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin with ID &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_Plugin_Details_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_Plugin_Details_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin new version must have value..
        /// </summary>
        internal static string Features_Plugin_Validation_NewVersion_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Plugin_Validation_NewVersion_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin old version must have value..
        /// </summary>
        internal static string Features_Plugin_Validation_OldVersion_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Plugin_Validation_OldVersion_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type must have value..
        /// </summary>
        internal static string Features_Plugin_Validation_Type_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Plugin_Validation_Type_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin version must have value..
        /// </summary>
        internal static string Features_Plugin_Validation_Version_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Plugin_Validation_Version_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Features_PluginConfig_Add_PluginConfigAlreadyExists {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Add_PluginConfigAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_PluginConfig_Add_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Add_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Features_PluginConfig_Update_PluginConfigAlreadyExists {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Update_PluginConfigAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_PluginConfig_Update_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Update_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config name must have value..
        /// </summary>
        internal static string Features_PluginConfig_Validation_Name_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Validation_Name_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for plugin config name is invalid. Only Latin alphabet characters (A–Z, a–z), numbers, and underscore are permitted..
        /// </summary>
        internal static string Features_PluginConfig_Validation_Name_OnlyAcceptLatingCharacters {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Validation_Name_OnlyAcceptLatingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config type must have value..
        /// </summary>
        internal static string Features_PluginConfig_Validation_Type_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Validation_Type_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config version must have value..
        /// </summary>
        internal static string Features_PluginConfig_Validation_Version_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Validation_Version_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_Id_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_Id_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id value must have value..
        /// </summary>
        internal static string Features_Validation_Id_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_Id_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow &apos;{0}&apos; is already exists..
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowAlreadyExists {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition must be not empty!.
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowDefinitionMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowDefinitionMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name must have value..
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowNameMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowNameMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string Features_Workflow_Delete_WorkflowCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_Workflow_Delete_WorkflowCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow &apos;{0}&apos; is already exists..
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowAlreadyExists {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition must be not empty!.
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowDefinitionMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowDefinitionMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name must have value..
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowNameMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowNameMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow definition must have value..
        /// </summary>
        internal static string Features_Workflow_Validation_Definition_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Validation_Definition_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowSynx Long Running Request: Request {0} took {1}ms.
        /// </summary>
        internal static string PerformanceBehavior_LongRunning_Request {
            get {
                return ResourceManager.GetString("PerformanceBehavior_LongRunning_Request", resourceCulture);
            }
        }
    }
}
