//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Please check and ensure you using a valid credentials..
        /// </summary>
        internal static string Authentication_Access_Denied {
            get {
                return ResourceManager.GetString("Authentication_Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit details, id &apos;{0}&apos;, are not found..
        /// </summary>
        internal static string Feature_Audit_DetailsNotFound {
            get {
                return ResourceManager.GetString("Feature_Audit_DetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been installed successfully..
        /// </summary>
        internal static string Feature_Plugin_Install_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Install_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been uninstalled successfully..
        /// </summary>
        internal static string Feature_Plugin_Uninstall_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Uninstall_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin has been updated successfully..
        /// </summary>
        internal static string Feature_Plugin_Update_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Plugin_Update_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been added successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Add_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Add_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config with ID &apos;{configId}&apos; was not found..
        /// </summary>
        internal static string Feature_PluginConfig_Delete_ConfigIdNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Delete_ConfigIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been deleted successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin config details for &apos;{0}&apos; has been retrieved successfully..
        /// </summary>
        internal static string Feature_PluginConfig_DetailesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_DetailesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plugin config details, id &apos;{0}&apos;, are not found..
        /// </summary>
        internal static string Feature_PluginConfig_DetailsNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_DetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Config List has been retrieved successfully..
        /// </summary>
        internal static string Feature_PluginConfig_ListRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_ListRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config with ID &apos;{configId}&apos; was not found..
        /// </summary>
        internal static string Feature_PluginConfig_Update_ConfigIdNotFound {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Update_ConfigIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config has been updated successfully..
        /// </summary>
        internal static string Feature_PluginConfig_Update_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_PluginConfig_Update_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been added successfully..
        /// </summary>
        internal static string Feature_Workflow_Add_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Add_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been deleted successfully..
        /// </summary>
        internal static string Feature_Workflow_Delete_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Delete_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin workflow details has been retrieved successfully..
        /// </summary>
        internal static string Feature_Workflow_Details_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Details_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_Workflow_Details_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_Workflow_Details_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin workflow has been retrieved successfully..
        /// </summary>
        internal static string Feature_Workflow_ListRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_ListRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has been updated successfully..
        /// </summary>
        internal static string Feature_Workflow_Update_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_Workflow_Update_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_Workflow_Update_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_Workflow_Update_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow &apos;{0}&apos; cancelled successfully!.
        /// </summary>
        internal static string Feature_WorkflowExecution_CancelledSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_CancelledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution details has been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowExecution_Details_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_Details_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowExecution_Details_ExecutionNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_Details_ExecutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow &apos;{0}&apos; executed successfully!.
        /// </summary>
        internal static string Feature_WorkflowExecution_ExecutedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_ExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executions list has been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowExecution_List_RetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_List_RetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution logs have been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowExecution_Logs_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowExecution_Logs_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Execution details has been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowTaskExecution_Details_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTaskExecution_Details_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task execution with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTaskExecution_Details_TaskExecutionNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTaskExecution_Details_TaskExecutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Execution logs have been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowTaskExecution_Logs_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTaskExecution_Logs_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow trigger with id &apos;{0}&apos; updated successfully!.
        /// </summary>
        internal static string Feature_WorkflowTrigger_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTrigger_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Add_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Add_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers with id &apos;{0}&apos; has been added successfully..
        /// </summary>
        internal static string Feature_WorkflowTriggers_AddedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Delete_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Delete_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task workflow trigger details has been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Details_DataRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Details_DataRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow trigger with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Details_TriggerNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Details_TriggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers list for workflow &apos;{0}&apos; has been retrieved successfully..
        /// </summary>
        internal static string Feature_WorkflowTriggers_List_RetrievedSuccessfully {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_List_RetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trigger with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Update_TriggerNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Update_TriggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; not found..
        /// </summary>
        internal static string Feature_WorkflowTriggers_Update_WorkflowNotFound {
            get {
                return ResourceManager.GetString("Feature_WorkflowTriggers_Update_WorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin with ID &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_Plugin_Details_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_Plugin_Details_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Features_PluginConfig_Add_PluginConfigAlreadyExists {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Add_PluginConfigAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_PluginConfig_Add_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Add_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config &apos;{0}&apos; already exists..
        /// </summary>
        internal static string Features_PluginConfig_Update_PluginConfigAlreadyExists {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Update_PluginConfigAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type &apos;{0}&apos; with version &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string Features_PluginConfig_Update_PluginCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_PluginConfig_Update_PluginCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_AuditId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_AuditId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id value must have value..
        /// </summary>
        internal static string Features_Validation_AuditId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_AuditId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid workflow Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_ExecutionId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_ExecutionId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow id value must have value..
        /// </summary>
        internal static string Features_Validation_ExecutionId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_ExecutionId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin new version must have value..
        /// </summary>
        internal static string Features_Validation_Plugin_NewVersion_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_Plugin_NewVersion_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin old version must have value..
        /// </summary>
        internal static string Features_Validation_Plugin_OldVersion_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_Plugin_OldVersion_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin type must have value..
        /// </summary>
        internal static string Features_Validation_Plugin_Type_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_Plugin_Type_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin version must have value..
        /// </summary>
        internal static string Features_Validation_Plugin_Version_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_Plugin_Version_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config name must have value..
        /// </summary>
        internal static string Features_Validation_PluginConfig_Name_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfig_Name_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for plugin config name is invalid. Only Latin alphabet characters (A–Z, a–z), numbers, and underscore are permitted..
        /// </summary>
        internal static string Features_Validation_PluginConfig_Name_OnlyAcceptLatingCharacters {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfig_Name_OnlyAcceptLatingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config type must have value..
        /// </summary>
        internal static string Features_Validation_PluginConfig_Type_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfig_Type_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config version must have value..
        /// </summary>
        internal static string Features_Validation_PluginConfig_Version_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfig_Version_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin config Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_PluginConfigId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfigId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin config id value must have value..
        /// </summary>
        internal static string Features_Validation_PluginConfigId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_PluginConfigId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_PluginId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_PluginId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin id value must have value..
        /// </summary>
        internal static string Features_Validation_PluginId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_PluginId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trigger Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_TriggerId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_TriggerId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trigger id value must have value..
        /// </summary>
        internal static string Features_Validation_TriggerId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_TriggerId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid workflow Id format. Please ensure the ID value  matches the standard GUID format (e.g., xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)..
        /// </summary>
        internal static string Features_Validation_WorkflowId_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Features_Validation_WorkflowId_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow id value must have value..
        /// </summary>
        internal static string Features_Validation_WorkflowId_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Validation_WorkflowId_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow &apos;{0}&apos; is already exists..
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowAlreadyExists {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition must be not empty!.
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowDefinitionMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowDefinitionMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name must have value..
        /// </summary>
        internal static string Features_Workflow_Add_WorkflowNameMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Add_WorkflowNameMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow with id &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string Features_Workflow_Delete_WorkflowCouldNotBeFound {
            get {
                return ResourceManager.GetString("Features_Workflow_Delete_WorkflowCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow &apos;{0}&apos; is already exists..
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowAlreadyExists {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition must be not empty!.
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowDefinitionMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowDefinitionMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow name must have value..
        /// </summary>
        internal static string Features_Workflow_Update_WorkflowNameMustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Update_WorkflowNameMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow definition must have value..
        /// </summary>
        internal static string Features_Workflow_Validation_Definition_MustHaveValue {
            get {
                return ResourceManager.GetString("Features_Workflow_Validation_Definition_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DefaultScheme &apos;{0}&apos;. Must be one of: {1}.
        /// </summary>
        internal static string SecurityConfiguration_InvalidScheme {
            get {
                return ResourceManager.GetString("SecurityConfiguration_InvalidScheme", resourceCulture);
            }
        }
    }
}
