//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Plugin.Storage.Azure.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Plugin.Storage.Azure.Files.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy operation for file &apos;{0} could not proceed!.
        /// </summary>
        internal static string CopyOperationCouldNotBeProceed {
            get {
                return ResourceManager.GetString("CopyOperationCouldNotBeProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered data is not valid. The data should be in string or Base64 format..
        /// </summary>
        internal static string EnteredDataIsNotValid {
            get {
                return ResourceManager.GetString("EnteredDataIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is already exist and can&apos;t be overwritten!.
        /// </summary>
        internal static string FileIsAlreadyExistAndCannotBeOverwritten {
            get {
                return ResourceManager.GetString("FileIsAlreadyExistAndCannotBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path entered..
        /// </summary>
        internal static string InvalidPathEntered {
            get {
                return ResourceManager.GetString("InvalidPathEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found with the given filter in &apos;{0}&apos;..
        /// </summary>
        internal static string NoFilesFoundWithTheGivenFilter {
            get {
                return ResourceManager.GetString("NoFilesFoundWithTheGivenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the ConnectionString or both AccountKey and AccountName properties in the azure file specifications should have value..
        /// </summary>
        internal static string OnePropertyShouldHaveValue {
            get {
                return ResourceManager.GetString("OnePropertyShouldHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parent path does not exist..
        /// </summary>
        internal static string ParentNotFound {
            get {
                return ResourceManager.GetString("ParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin for managing Microsoft Azure File storage system..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; not exist!.
        /// </summary>
        internal static string ResourceNotExist {
            get {
                return ResourceManager.GetString("ResourceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Item &apos;{0}&apos; not found..
        /// </summary>
        internal static string ShareItemNotFound {
            get {
                return ResourceManager.GetString("ShareItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ShareName value in azure file specifications should be not empty..
        /// </summary>
        internal static string ShareNameInSpecificationShouldBeNotEmpty {
            get {
                return ResourceManager.GetString("ShareNameInSpecificationShouldBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happened during processing existing file on Azure file share!.
        /// </summary>
        internal static string SomethingWrongHappenedDuringProcessingExistingFile {
            get {
                return ResourceManager.GetString("SomethingWrongHappenedDuringProcessingExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered path is not a directory..
        /// </summary>
        internal static string ThePathIsNotDirectory {
            get {
                return ResourceManager.GetString("ThePathIsNotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered path is not a file..
        /// </summary>
        internal static string ThePathIsNotFile {
            get {
                return ResourceManager.GetString("ThePathIsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path must be a file. Please specified a file path..
        /// </summary>
        internal static string ThePathMustBeFile {
            get {
                return ResourceManager.GetString("ThePathMustBeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory path &apos;{0}&apos; is not a directory..
        /// </summary>
        internal static string TheSpecifiedDirectoryPathIsNotDirectory {
            get {
                return ResourceManager.GetString("TheSpecifiedDirectoryPathIsNotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path &apos;{0}&apos; is not exist..
        /// </summary>
        internal static string TheSpecifiedPathIsNotExist {
            get {
                return ResourceManager.GetString("TheSpecifiedPathIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path &apos;{0}&apos; is not a file..
        /// </summary>
        internal static string TheSpecifiedPathIsNotFile {
            get {
                return ResourceManager.GetString("TheSpecifiedPathIsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path must be not empty!.
        /// </summary>
        internal static string TheSpecifiedPathMustBeNotEmpty {
            get {
                return ResourceManager.GetString("TheSpecifiedPathMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified resource name contains invalid characters..
        /// </summary>
        internal static string TheSpecifiedResourceNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("TheSpecifiedResourceNameContainsInvalidCharacters", resourceCulture);
            }
        }
    }
}
