### Config
POST {{FlowSynxAddress}}/config
Content-Type: application/json

{
  "type": ""
}


###ConfigDetails
GET {{FlowSynxAddress}}/config/details/azblob
Content-Type: application/json


###AddConfig
POST {{FlowSynxAddress}}/config/add
Content-Type: application/json

{ 
  "name": "azblob", 
  "type": "FlowSynx.Storage/Azure.Blobs", 
  "specifications": {
    "AccountKey": "<ACCOUNT_KEY>",
    "AccountName": "<ACCOUNT_NAME>"
  } 
}


### DeleteConfig
DELETE {{FlowSynxAddress}}/config/delete
Content-Type: application/json

{
  "name": "http"
}