//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowSynx.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlowSynxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlowSynxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowSynx.Localization.FlowSynxResources", typeof(FlowSynxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration service.
        /// </summary>
        internal static string AddHealthCheckerConfigurationService {
            get {
                return ResourceManager.GetString("AddHealthCheckerConfigurationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger service.
        /// </summary>
        internal static string AddHealthCheckerLoggerService {
            get {
                return ResourceManager.GetString("AddHealthCheckerLoggerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Please check and ensure you using a valid credentials..
        /// </summary>
        internal static string Authentication_Access_Denied {
            get {
                return ResourceManager.GetString("Authentication_Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration service is available.
        /// </summary>
        internal static string ConfigurationServiceHealthCheckConfigurationServiceAvailable {
            get {
                return ResourceManager.GetString("ConfigurationServiceHealthCheckConfigurationServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration service is failed.
        /// </summary>
        internal static string ConfigurationServiceHealthCheckConfigurationServiceFailed {
            get {
                return ResourceManager.GetString("ConfigurationServiceHealthCheckConfigurationServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happen during execute the application..
        /// </summary>
        internal static string EntryPointErrorInExecutteApplication {
            get {
                return ResourceManager.GetString("EntryPointErrorInExecutteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed. Please check the connection details..
        /// </summary>
        internal static string FailDatabaseConnection {
            get {
                return ResourceManager.GetString("FailDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database initialization failed..
        /// </summary>
        internal static string FailedDatabaseInitialization {
            get {
                return ResourceManager.GetString("FailedDatabaseInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base location not found.
        /// </summary>
        internal static string FlowSynxLocationBaseLocationNotFound {
            get {
                return ResourceManager.GetString("FlowSynxLocationBaseLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root location not found.
        /// </summary>
        internal static string FlowSynxLocationRootLocationNotFound {
            get {
                return ResourceManager.GetString("FlowSynxLocationRootLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntryAssembly not found. Getting ExecutingAssembly!.
        /// </summary>
        internal static string FlowSynxVersionEntryAssemblyNotFound {
            get {
                return ResourceManager.GetString("FlowSynxVersionEntryAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in reading executable application..
        /// </summary>
        internal static string FlowSynxVersionErrorInReadingExecutableApplication {
            get {
                return ResourceManager.GetString("FlowSynxVersionErrorInReadingExecutableApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger Service is failed.
        /// </summary>
        internal static string LoggerServiceHealthCheckFailed {
            get {
                return ResourceManager.GetString("LoggerServiceHealthCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger service is available.
        /// </summary>
        internal static string LoggerServiceHealthCheckLoggerServiceAvailable {
            get {
                return ResourceManager.GetString("LoggerServiceHealthCheckLoggerServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger Service is failed.
        /// </summary>
        internal static string LoggerServiceHealthCheckLoggerServiceFailed {
            get {
                return ResourceManager.GetString("LoggerServiceHealthCheckLoggerServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in reading executable application path..
        /// </summary>
        internal static string OptionsVerifierErrorInReadingExecutableApplicationPath {
            get {
                return ResourceManager.GetString("OptionsVerifierErrorInReadingExecutableApplicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered config file &apos;{0}&apos; is not exist!.
        /// </summary>
        internal static string OptionsVerifierTheEnteredConfigFileIsNotExist {
            get {
                return ResourceManager.GetString("OptionsVerifierTheEnteredConfigFileIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins service is available.
        /// </summary>
        internal static string PluginServiceHealthCheckPluginServiceAvailable {
            get {
                return ResourceManager.GetString("PluginServiceHealthCheckPluginServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Service is failed.
        /// </summary>
        internal static string PluginServiceHealthCheckPluginServiceFailed {
            get {
                return ResourceManager.GetString("PluginServiceHealthCheckPluginServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version service could not be initialized..
        /// </summary>
        internal static string UseCustomHeadersVersionServiceCouldNotBeInitialized {
            get {
                return ResourceManager.GetString("UseCustomHeadersVersionServiceCouldNotBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer service could not be initialized..
        /// </summary>
        internal static string UseHealthCheckSerializerServiceCouldNotBeInitialized {
            get {
                return ResourceManager.GetString("UseHealthCheckSerializerServiceCouldNotBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified workflow queue provider &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string WorkflowQueueProvider_NotSupported {
            get {
                return ResourceManager.GetString("WorkflowQueueProvider_NotSupported", resourceCulture);
            }
        }
    }
}
